# Generated by Django 3.0.3 on 2020-02-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_model',
            name='year_in_school',
            field=models.CharField(choices=[('DY', 'Daily'), ('WY', 'Weekly'), ('MY', 'Monthly')], default=True, max_length=2),
            preserve_default=False,
        ),
    ]
